---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: default
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.pkg.github.com/jthiry50/hello/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "0.5"
            memory: 500m
          requests:
            cpu: "0.5"
            memory: 500m
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
spec:
  rules:
  - host: hello.cluster.local
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 8080
  - host: hello2.cluster.local
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`hello.cluster.local`)
    kind: Rule
    services:
    - name: hello-service
      port: 8080