---
apiVersion: v1
kind: Namespace
metadata:
  name: hello
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: hello
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.pkg.github.com/jltio/hello/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        # resources:
        #   limits:
        #     cpu: "0.5"
        #     memory: 500m
        #   requests:
        #     cpu: "0.5"
        #     memory: 500m
        # readinessProbe:
        #   httpGet:
        #     path: /healthz
        #     port: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  namespace: hello
  labels:
    app: hello
spec:
  selector:
    app: hello
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: hello
spec:
  rules:
  - host: hello.cluster.local
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 8080
  - host: hello2.cluster.local
    http:
      paths:
      - backend:
          serviceName: hello-service
          servicePort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: hello-ingressroute
  namespace: hello
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`hello.local`)
    services:
    - Kind: Service
      name: hello-service
      namespace: hello
      port: 8080
