apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: dokuwiki-1591030019
    meta.helm.sh/release-namespace: default
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: dokuwiki
    app.kubernetes.io/managed-by: Helm
    chart: dokuwiki-6.0.11
    heritage: Helm
    release: dokuwiki-1591030019
  name: dokuwiki-1591030019-dokuwiki
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: local-path
