name: Build and Push Docker Image
on:
  push:
    branches:
      - master
env:
  registry_hostname: docker.pkg.github.com
  image_name: hello
  version: latest
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image
        run: docker build -t ${registry_hostname}/${{ github.repository }}/${image_name}:${version} .

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ${registry_hostname}/${{ github.repository }}/${image_name}:${version}
